from .testOrSettings import test_or_settings_markup
from .category import category_markup
from .subcategory import create_sub_category_markup
from .type_question import create_type_of_question_markup
